//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidoClickAPI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pedidoclick : DbContext
    {
        public pedidoclick()
            : base("name=pedidoclick")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Mensajes> t_Mensajes { get; set; }
        public virtual DbSet<t_Categoria> t_Categoria { get; set; }
        public virtual DbSet<t_Cliente> t_Cliente { get; set; }
        public virtual DbSet<t_Producto> t_Producto { get; set; }
        public virtual DbSet<t_Rol> t_Rol { get; set; }
        public virtual DbSet<t_Sesion> t_Sesion { get; set; }
        public virtual DbSet<t_Usuario> t_Usuario { get; set; }
        public virtual DbSet<t_Orden> t_Orden { get; set; }
        public virtual DbSet<t_OrdenDetalle> t_OrdenDetalle { get; set; }
        public virtual DbSet<t_OrdenEstado> t_OrdenEstado { get; set; }
        public virtual DbSet<t_Tienda> t_Tienda { get; set; }
        public virtual DbSet<t_CategoriaTienda> t_CategoriaTienda { get; set; }
    
        public virtual int SP_Categoria_Crear(string sesionId, string categoria, Nullable<int> tiendaId)
        {
            var sesionIdParameter = sesionId != null ?
                new ObjectParameter("sesionId", sesionId) :
                new ObjectParameter("sesionId", typeof(string));
    
            var categoriaParameter = categoria != null ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(string));
    
            var tiendaIdParameter = tiendaId.HasValue ?
                new ObjectParameter("tiendaId", tiendaId) :
                new ObjectParameter("tiendaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Categoria_Crear", sesionIdParameter, categoriaParameter, tiendaIdParameter);
        }
    
        public virtual ObjectResult<SP_Categoria_List_Result> SP_Categoria_List(Nullable<int> clientId, Nullable<int> tiendaId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(int));
    
            var tiendaIdParameter = tiendaId.HasValue ?
                new ObjectParameter("tiendaId", tiendaId) :
                new ObjectParameter("tiendaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Categoria_List_Result>("SP_Categoria_List", clientIdParameter, tiendaIdParameter);
        }
    }
}
