//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidoClickAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_OrdenDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaBorro { get; set; }
        public Nullable<int> IdUsuarioBorro { get; set; }
        public Nullable<bool> Borrado { get; set; }
    
        public virtual t_Orden t_Orden { get; set; }
        public virtual t_Producto t_Producto { get; set; }
        public virtual t_Usuario t_Usuario { get; set; }
    }
}
